version: '2'

volumes:
  db_data:

services:
  db:
    container_name: 'postgres'
    image: mdillon/postgis
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
      - db
